### ISSUE TITLE
Unknown value 'Dolby Surround' in TwoChDecoder

### ISSUE THREAD

**Issue by dan-s-github** [mvdwetering/yamaha_ynca#207]
**Describe the bug**
I am using this integration with a Yamaha RX-A3070
After restarting Home Assistant I always find the mentioned warning in the logs

**To Reproduce**

**Expected behavior**

**Diagnostics**
[config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json.txt](https://github.com/mvdwetering/yamaha_ynca/files/12779594/config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json.txt)

**Logging**
Error in Home Assistant Core

```
Logger: ynca.enums
Source: /usr/local/lib/python3.11/site-packages/ynca/enums.py:409
First occurred: 4:54:13 PM (1 occurrences)
Last logged: 4:54:13 PM

Unknown value 'Dolby Surround' in TwoChDecoder
```

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2023.9.2
- Home Assistant operating environment (OS/Container/Supervised/Core): OS 10.5
- Yamaha YNCA: 7.5.0

**Additional context**
Everything works fine and I haven't noticed any issues so far.

**Comment by mvdwetering** [comment]
Newer receivers seems to support more/different surround decoder modes. Your receiver has a value I have not seen before, so there is no mapping.

From the manual it seems your receiver also has an "Auto" mode which is probably also missing. Could you cycle through all the modes and attach the diagnostics again? I can then add all the modes that are missing in one go.

![image](https://github.com/mvdwetering/yamaha_ynca/assets/732514/72e8f5fb-ccb0-4ce9-b2b1-13bcad69705a)



The part your are missing from the integration is the surround decoder selection. See screenshot to see how it looks for my receiver. If it would be useful I can try adding it for other receivers, but I don't think I can autodetect which soundmodes are supported for a receiver so that would be another list in the settings like soundmodes/inputs where you would need to manually select supported surround decoders.

![image](https://github.com/mvdwetering/yamaha_ynca/assets/732514/4a346dbc-168c-40b4-b286-dd6c0a8f78dc)

**Comment by dan-s-github** [comment]
Ok, I cycled through the surround modes

[config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json-2.txt](https://github.com/mvdwetering/yamaha_ynca/files/12788418/config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json-2.txt)

**Comment by mvdwetering** [comment]
Thanks for the complete list of Surround decoder modes. Will try to get at least the list update released fast so the errors are gone. 

Making it configurable in the integration configuration will take a bit longer as it is more complicated to build. But when that is done the Surround Decoder selection should show up for all receivers.

The list of entities for your receiver seems to be complete as far as I can tell.
Only thing I see missing compared to my receiver are the bass/treble controls for headphones and speakers. From the diagnostics it looks like your receiver does support some kind of treble/bass control but uses different commands for it (TONETREBEL and TONEBASS). If it would be useful I can add those controls, but I would need more info on what the range and stepsize are and there is also a TONEMODE (only for zone 2 and 3) which is probably related to the bass/treble control.

Do you feel anything else is missing?

**Comment by dan-s-github** [comment]
First I want to thank you for making this integration available. 

As the receiver is in my media room and only used to watch Movies I don’t actually need tone control as I am quite happy with the automatic room correction.
I only use the main zone the rest of the house uses C4 Matrix and AMP.

But I might try to loop through the setting to provide some details on the weekend, just in case.

**Comment by mvdwetering** [comment]
FYI I just released v7.5.1 which should get rid of the warning.

I will keep this issue open as a reminder to make the surround decoder values more extendible so it should work for all receivers.

**Comment by dan-s-github** [comment]
Updated to latest version but still don't see the Surround Decoder options but log warning is gone

Attached is a diagnostic log including the tone control information. I never used this option as I optimised room using  YPAQ.
 
[config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json-3.txt](https://github.com/mvdwetering/yamaha_ynca/files/12843325/config_entry-yamaha_ynca-a5c3d179eae68e0c6def24ff16a2248f.json-3.txt)

**Comment by mvdwetering** [comment]
>  but still don't see the Surround Decoder options

That is expected, the 7.5.1 update only got rid of the warning (and a few other small things that were pending).

The current surround decoder entity only supports a fixed set of values. Extending it to make it support the other modes you found and have them configurable by the user (as it can't be autodetected) is more work for which I unfortunately don't have time right now. I will pick this up later.

Thanks for the log. I would be able to add the bass/treble for your receiver with that.

**Comment by mvdwetering** [comment]
Sorry for the long wait. I finally got around implementing support for all (currently) known surround decoders in v7.6.0.

Note that you will have to select the surround decoders supported by your receiver in the integration configuration as it can not be automatically detected.

**Comment by dan-s-github** [comment]
No worries, I don't actually use HA to control the receiver as it is only used in the media-room to basically watch movies which is mostly Netflix. But this might change soon if I can get the Samsung projector and the Yamaha Receiver to work nicely together in HA.
Fix looks great and I could configure my supported surround decoders.
![image](https://github.com/mvdwetering/yamaha_ynca/assets/20974454/bd54afd1-be46-424d-bffb-b91ce2f42b48)
Thanks for getting this implemented
